server:
  port: 4000
  idle-timeout: 1m
  read-timeout: 10s
  write-timeout: 30s
  shutdown-timeout: 5s
logger:
  level: info
  writers:
    - console
data:
  query-timeout: 3s
  max-open-conns: 25
  max-idle-conns: 25
  idle-timeout: 15m
  ping-timeout: 5s